# Generated by Django 4.1 on 2022-10-23 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("works", "0003_rename_last_updated_date_work_date_published_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="work",
            name="metadata",
            field=models.JSONField(default={}),
        ),
    ]
