# Generated by Django 4.1 on 2022-10-20 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("works", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="work",
            old_name="completed",
            new_name="last_updated_date",
        ),
        migrations.RenameField(
            model_name="work",
            old_name="last_updated",
            new_name="posted_date",
        ),
        migrations.RemoveField(
            model_name="work",
            name="posted",
        ),
        migrations.AddField(
            model_name="work",
            name="platform_id",
            field=models.CharField(
                help_text="ID of the work on the platform (AO3, FFN, etc.)",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="author",
            name="url",
            field=models.URLField(help_text="URL to the author"),
        ),
        migrations.AlterField(
            model_name="author",
            name="username",
            field=models.CharField(help_text="Author's username", max_length=100),
        ),
    ]
